import style from '../styles/global.module.scss'
import Navigation from '../components/Navigation/Navigation'
import Footer from '../components/Footer/Footer'

export const metadata = {
  title: 'Mercado libre',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  // eslint-disable-next-line no-undef
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={style.body}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
